application-properties.message-topic.new-comment.topic-name=new-comment
application-properties.message-topic.new-comment.type=NEW_COMMENT
application-properties.message-topic.new-post.topic-name=new-post
application-properties.message-topic.new-post.type=NEW_POST
application-properties.message-topic.new-subscriber.topic-name=new-subscriber
application-properties.message-topic.new-subscriber.type=NEW_SUBSCRIBER
application-properties.message-topic.new-post-following.topic-name=new-post-following
application-properties.message-topic.new-post-following.type=NEW_POST_FOLLOWING
application-properties.message-topic.key-invalidated.topic-name=key-invalidated