package com.vulinh.service;

import com.querydsl.core.types.Predicate;
import com.vulinh.data.base.AbstractEntity;
import com.vulinh.utils.PredicateBuilder;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.querydsl.ListQuerydslPredicateExecutor;
import org.springframework.lang.NonNull;
import org.springframework.lang.Nullable;

/**
 * A generic service interface for handling paginated queries using QueryDSL.
 *
 * <p>Type parameters:
 *
 * @param <E> The type of the JPA entity. This type must extend AbstractIdentifiable and is expected
 *     to be an entity managed by the repository provided in getDslRepository().
 * @param <D> The type of the Data Transfer Object (DTO) to which the entity will be converted.
 * @param <S> The type of the search criteria object used to build the query predicate.
 */
public interface PageableQueryService<E extends AbstractEntity<?>, D, S> {

  /**
   * Converts a given entity instance into its corresponding DTO representation. Implementations
   * typically delegate this conversion to a dedicated mapper component, such as one generated by
   * MapStruct or configured with ModelMapper.
   *
   * @param entity The non-null entity to convert.
   * @return The non-null DTO representation of the entity.
   */
  @NonNull
  D toDto(@NonNull E entity);

  /**
   * Builds a QueryDSL {@link Predicate} from the given search criteria object. Implementations can
   * return null if the search criteria should result in no filtering (i.e., match all records). The
   * default {@link PageableQueryService#search(Object, Pageable)} method handles a null predicate
   * gracefully.
   *
   * @param searchCriteria – The non-null object containing search parameters.
   * @return A Predicate for filtering, or null if no specific filtering is needed.
   */
  @Nullable
  Predicate buildSearchPredicate(@NonNull S searchCriteria);

  /**
   * Provides the repository instance that supports QueryDSL predicate execution.
   *
   * @return The non-null {@link ListQuerydslPredicateExecutor} instance for the entity E.
   */
  @NonNull
  ListQuerydslPredicateExecutor<E> getRepository();

  @NonNull
  default Page<D> search(@NonNull S searchCriteria, @NonNull Pageable pageable) {
    var predicate = buildSearchPredicate(searchCriteria);

    return getRepository()
        .findAll(predicate == null ? PredicateBuilder.always() : predicate, pageable)
        .map(this::toDto);
  }
}
