package com.vulinh.data.base;

import java.io.Serializable;

/**
 * Record-flavored variant of {@link Identifiable} that exposes the identifier through {@link
 * #id()}, the naming convention used by Java record component accessors, rather than the classic
 * JavaBean-style {@link #getId()}.
 *
 * <p>Any Java record declaring an {@code id} component of type {@code I} automatically satisfies
 * this interface; the canonical accessor generated by the record is the implementation of {@link
 * #id()}, and {@link #getId()} is provided as a default bridge so the record still fulfils the
 * broader {@link Identifiable} contract.
 *
 * <pre>{@code
 * public record UserResponse(UUID id, String username)
 *     implements RecordIdentifiable<UUID> {}
 * }</pre>
 *
 * @param <I> the type of the identifier, must be {@link Serializable}.
 */
@FunctionalInterface
public interface RecordIdentifiable<I extends Serializable> extends Identifiable<I> {

  @Override
  default I getId() {
    return id();
  }

  /**
   * Returns the unique identifier of this record.
   *
   * @return the identifier value.
   */
  I id();
}
